"use client";

import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import StatCard from "@/components/StatCard";
import { api } from "@/lib/api";
import type { Activity, ResponseItem, SessionInfo, Student } from "@/lib/types";

interface SessionDetail {
  session: SessionInfo;
  activity: Activity;
  students: Student[];
  responses: ResponseItem[];
}

export default function LiveSessionPage() {
  const params = useParams<{ sessionId: string }>();
  const sessionId = params.sessionId;
  const [detail, setDetail] = useState<SessionDetail | null>(null);
  const [ending, setEnding] = useState(false);

  useEffect(() => {
    let cancelled = false;
    api.get<SessionDetail>(`/api/sessions/${sessionId}`).then((d) => {
      if (!cancelled) setDetail(d);
    });
    return () => {
      cancelled = true;
    };
  }, [sessionId]);

  useEffect(() => {
    if (!detail) return;
    const wsBase = api.base.replace(/^http/, "ws");
    const ws = new WebSocket(`${wsBase}/api/ws/session/${detail.session.code}`);

    ws.onmessage = (event) => {
      const msg = JSON.parse(event.data);
      setDetail((prev) => {
        if (!prev) return prev;
        if (msg.type === "student_joined") {
          return { ...prev, students: [...prev.students, msg.student] };
        }
        if (msg.type === "response_submitted") {
          return { ...prev, responses: [...prev.responses, msg.response] };
        }
        return prev;
      });
    };

    return () => ws.close();
    // Only reconnect when the session code changes, not on every response.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [detail?.session.code]);

  async function handleEnd() {
    if (!detail) return;
    setEnding(true);
    try {
      await api.post(`/api/sessions/${detail.session.id}/end`);
      setDetail((prev) => (prev ? { ...prev, session: { ...prev.session, status: "ended" } } : prev));
    } finally {
      setEnding(false);
    }
  }

  if (!detail) {
    return <p className="text-sm text-slate-500">Loading session...</p>;
  }

  const { session, activity, students, responses } = detail;
  const completionRate = students.length ? Math.round((responses.length / students.length) * 100) : 0;

  return (
    <div>
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold text-slate-900 dark:text-white">{activity.title}</h1>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
            Session code <span className="font-mono font-semibold text-brand-600">{session.code}</span> &middot;{" "}
            <span className={session.status === "active" ? "text-green-600" : "text-slate-400"}>
              {session.status}
            </span>
          </p>
        </div>
        {session.status === "active" && (
          <button
            onClick={handleEnd}
            disabled={ending}
            className="rounded-lg border border-red-300 px-4 py-2 text-sm font-semibold text-red-600 hover:bg-red-50 disabled:opacity-50 dark:border-red-800 dark:hover:bg-red-950"
          >
            {ending ? "Ending..." : "End Session"}
          </button>
        )}
      </div>

      <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-3">
        <div className="rounded-2xl border border-slate-200 bg-white p-5 text-center dark:border-slate-800 dark:bg-slate-900">
          <p className="text-sm text-slate-500 dark:text-slate-400">Scan to join</p>
          {/* Dynamically generated by the backend; not a static asset, so next/image doesn't apply here. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={`${api.base}/api/sessions/${session.id}/qrcode.png`}
            alt="Session QR code"
            className="mx-auto mt-3 h-40 w-40"
          />
          <p className="mt-3 break-all text-xs text-slate-500 dark:text-slate-400">{session.join_url}</p>
        </div>

        <div className="grid grid-cols-3 gap-4 lg:col-span-2">
          <StatCard label="Students Joined" value={students.length} />
          <StatCard label="Responses" value={responses.length} />
          <StatCard label="Completion" value={`${completionRate}%`} />
        </div>
      </div>

      <div className="mt-8 grid grid-cols-1 gap-6 lg:grid-cols-2">
        <div>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-white">Students</h2>
          {students.length === 0 ? (
            <p className="text-sm text-slate-500">No one has joined yet.</p>
          ) : (
            <ul className="space-y-2">
              {students.map((s) => (
                <li key={s.id} className="rounded-lg border border-slate-200 px-4 py-2 text-sm dark:border-slate-800">
                  {s.name} {s.grade && `· Grade ${s.grade}`} {s.section && `· ${s.section}`}
                </li>
              ))}
            </ul>
          )}
        </div>

        <div>
          <h2 className="mb-2 text-lg font-semibold text-slate-900 dark:text-white">Live responses</h2>
          {responses.length === 0 ? (
            <p className="text-sm text-slate-500">Waiting for the first response...</p>
          ) : (
            <ul className="space-y-2">
              {responses.map((r) => {
                const student = students.find((s) => s.id === r.student_id);
                return (
                  <li
                    key={r.id}
                    className="flex items-center justify-between rounded-lg border border-slate-200 px-4 py-2 text-sm dark:border-slate-800"
                  >
                    <span>{student?.name ?? "Unknown student"}</span>
                    <span
                      className={
                        r.correct ? "text-green-600" : r.correct === false ? "text-red-500" : "text-slate-400"
                      }
                    >
                      {r.answer || (r.correct ? "Correct" : "Incorrect")}
                    </span>
                  </li>
                );
              })}
            </ul>
          )}
        </div>
      </div>
    </div>
  );
}
